version: "3"

services:

  psychics_backend:
    container_name: psychics_backend
    build:
      context: ./psychics/
    expose:
      - 8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.envs.prod
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx/
    ports:
      - 80:80
    depends_on:
      - psychics_backend
